# -*- coding: utf-8 -*-
"""yolov10ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13K7hmWvP3nj22yrfSrfKcJSN5i_S4mIP
"""

!git clone https://github.com/THU-MIG/yolov10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10
!pip install -q -r requirements.txt
!pip install -e

!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt

!pip install --upgrade ultralytics

from ultralytics import YOLOv10
model_path = 'yolov10n.pt'
model = YOLOv10(model_path)

!gdown 1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R

!mkdir safety_helmet_dataset
!unzip -q '/content/yolov10/Safety_Helmet_Dataset.zip' -d '/content/safety_helmet_dataset'

yaml_path ='/content/safety_helmet_dataset/data.yaml'
epoch = 50
batch_size = 32
img_size =640

model.train(data = yaml_path,
            epochs = epoch,
            batch = batch_size,
            imgsz = img_size)

trained_model_path = '/content/yolov10/runs/detect/train/weights/best.pt'
model_test = YOLOv10(trained_model_path)

model.val(data = yaml_path,
          imgsz = img_size,
          split = 'test')